# .streamlit/config.toml

[server]
headless = true  # 通常はサーバーモードなのでtrueに設定
open_browser = false  # Streamlit Cloudではブラウザを開く必要がないのでfalseに

# ページの設定
[theme]
base="light"

# アプリのタイトルとメニューの名称を設定
[general]
pageTitle = "REXLI InsightHub"  # ページのタイトルを変更
appMenuItem = "Home"            # メニュー項目の名前を変更
